### ISSUE TITLE
Command is not available error

### ISSUE THREAD

**Issue by codemeleon** [james9909/stackanswers.vim#12]
Hi,

I am getting following error when I try to execute the command.

_Error detected while processing function stackanswers#StackAnswers:
line    6:
E319: Sorry, the command is not available in this version: pyfile /home/devil/.vim/bundle/stackanswers.vim/autoload/stackanswers.py
line    7:
E319: Sorry, the command is not available in this version:         python stackAnswersVim("a:2")_

Thanks

**Comment by james9909** [comment]
Do you have python installed?

**Comment by codemeleon** [comment]
Yes, I do. Suggested python modules are also installed.

**Comment by james9909** [comment]
Apparently this issue may happen if your version of vim doesn't support python. This plugin requires vim to be built with python 2. Does `vim --version` include "+python"?

**Comment by codemeleon** [comment]
I think, it compile with python3.

**Comment by james9909** [comment]
Okay, that's a problem since this plugin expects python 2. I'll try and make it work with python 3 when I have some time.

**Comment by codemeleon** [comment]
Thanks. I mean time, I will try myself to make it work with python3.

**Comment by james9909** [comment]
This should be resolved now. Please let me know if you're still having issues. (See f20959e7a4e63c38e499c926931a3962ca786840)

**Comment by joshpetit** [comment]
Hey, so I'm still receiving this error:
```
Error detected while processing function stackanswers#StackAnswers:
line   14:
E319: Sorry, the command is not available in this version:         python stackAnswersVim("a:2")
```
