### ISSUE TITLE
StackExchange API

### ISSUE THREAD

**Issue by james9909** [james9909/stackanswers.vim#4]
Stack Exchange offers an API, and it might be a good idea to implement it. However, unless users authenticate, requests are limited to 300 per day.

**Comment by dthree** [comment]
:+1: on this plugin btw.

And I agree you should use the API. I just did something similar with [wat](https://github.com/dthree/wat), and the API helped a ton.

You can rip off my code if you want, to get started:

https://github.com/dthree/wat/blob/master/src/spider/stackoverflow.js

**Comment by lfv89** [comment]
I understand that using the API will make it easier to do everything in bash script, removing the python or any other language and packages dependencies.

Is my understanding correct? If it is will give me the "courage" I need to begin the PR.

What you guys think?

**Comment by james9909** [comment]
The API returns json, and we'd still need to parse that. It would remove the dependency on lxml and beautifulsoup, and the requests module could be replaced with urllib. However, I'd still like to use python, as vim has support for plugins with python. 

I am going to work on it, but currently I am swamped with homework.

**Comment by lfv89** [comment]
Well I can't use this plugin for this reason exactly; I can't make neovim and python to play along.

Anyway, thanks for the feedback. The worst part will be parsing the json in bs, but I'm sure I will find a lib to help me. When I'm finished I will sent the PR nevertheless.

**Comment by james9909** [comment]
Strange, since I can run the plugin just fine in neovim. Make sure that `:echo has("python")` returns 1, otherwise you should run `sudo pip install neovim`.

**Comment by grepsuzette** [comment]
Vim 8.0 has json support now, and lot of new features.
